/* tslint:disable */
/* eslint-disable */
/**
 * Autotab API
 * AI that does your repetitive work end to end, with superhuman reliability.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunSkillRequest
 */
export interface RunSkillRequest {
    /**
     * 
     * @type {string}
     * @memberof RunSkillRequest
     */
    skillId: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RunSkillRequest
     */
    inputs?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the RunSkillRequest interface.
 */
export function instanceOfRunSkillRequest(value: object): value is RunSkillRequest {
    if (!('skillId' in value) || value['skillId'] === undefined) return false;
    return true;
}

export function RunSkillRequestFromJSON(json: any): RunSkillRequest {
    return RunSkillRequestFromJSONTyped(json, false);
}

export function RunSkillRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunSkillRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'skillId': json['skill_id'],
        'inputs': json['inputs'] == null ? undefined : json['inputs'],
    };
}

  export function RunSkillRequestToJSON(json: any): RunSkillRequest {
      return RunSkillRequestToJSONTyped(json, false);
  }

  export function RunSkillRequestToJSONTyped(value?: RunSkillRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skill_id': value['skillId'],
        'inputs': value['inputs'],
    };
}

