/* tslint:disable */
/* eslint-disable */
/**
 * Autotab API
 * AI that does your repetitive work end to end, with superhuman reliability.
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VariableDataType = {
    String: 'string',
    Number: 'number',
    Boolean: 'boolean',
    Array: 'array',
    Object: 'object',
    File: 'file',
    Tab: 'tab'
} as const;
export type VariableDataType = typeof VariableDataType[keyof typeof VariableDataType];


export function instanceOfVariableDataType(value: any): boolean {
    for (const key in VariableDataType) {
        if (Object.prototype.hasOwnProperty.call(VariableDataType, key)) {
            if (VariableDataType[key as keyof typeof VariableDataType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VariableDataTypeFromJSON(json: any): VariableDataType {
    return VariableDataTypeFromJSONTyped(json, false);
}

export function VariableDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VariableDataType {
    return json as VariableDataType;
}

export function VariableDataTypeToJSON(value?: VariableDataType | null): any {
    return value as any;
}

export function VariableDataTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): VariableDataType {
    return value as VariableDataType;
}

